blank_issues_enabled: false
contact_links:
  - name: 📚 Documentation
    url: https://github.com/dyatlovk/ws_server/blob/master/README.md
    about: Check the comprehensive documentation and examples
  - name: 💬 Discussions
    url: https://github.com/dyatlovk/ws_server/discussions
    about: Ask questions and discuss ideas with the community
  - name: 🔧 Contributing Guide
    url: https://github.com/dyatlovk/ws_server/blob/master/CONTRIBUTING.md
    about: Learn how to contribute to the project
