name: Feature Request
description: Suggest a new feature or enhancement for WS Server
title: "[FEATURE] "
labels: ["enhancement", "needs-triage"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a new feature! Please provide as much detail as possible to help us understand your request.

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: Is your feature request related to a problem? Please describe.
      placeholder: I'm always frustrated when...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: Describe the solution you'd like to see implemented.
      placeholder: I would like to see...
    validations:
      required: true

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: Describe any alternative solutions or features you've considered.

  - type: dropdown
    id: component
    attributes:
      label: Component
      description: Which component of WS Server would this feature affect?
      options:
        - HTTP Server Core
        - Routing System
        - I/O and Sockets
        - Middleware
        - JSON Handling
        - Static File Serving
        - Testing Framework
        - Build System
        - Documentation
        - Examples
        - Other
    validations:
      required: true

  - type: dropdown
    id: priority
    attributes:
      label: Priority
      description: How important is this feature to you?
      options:
        - Low - Nice to have
        - Medium - Would be helpful
        - High - Important for my use case
        - Critical - Blocking my project

  - type: textarea
    id: use_case
    attributes:
      label: Use Case
      description: Describe your specific use case for this feature.
      placeholder: I need this feature because...

  - type: textarea
    id: implementation
    attributes:
      label: Implementation Ideas
      description: If you have ideas about how this could be implemented, please share them.

  - type: textarea
    id: examples
    attributes:
      label: Code Examples
      description: Provide examples of how you envision using this feature.
      render: cpp

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched for existing feature requests
          required: true
        - label: This feature would benefit multiple users
          required: true
        - label: I have provided sufficient detail about the request
          required: true
