name: Question
description: Ask a question about WS Server usage or development
title: "[QUESTION] "
labels: ["question", "needs-response"]
assignees: []

body:
  - type: markdown
    attributes:
      value: |
        Have a question about WS Server? We're here to help! Please provide as much context as possible.

  - type: dropdown
    id: category
    attributes:
      label: Question Category
      description: What category does your question fall into?
      options:
        - Installation and Setup
        - Usage and API
        - Performance and Optimization
        - Examples and Tutorials
        - Contributing and Development
        - Build System and Dependencies
        - Testing and Debugging
        - Other
    validations:
      required: true

  - type: textarea
    id: question
    attributes:
      label: Your Question
      description: Please ask your question in detail.
      placeholder: What would you like to know?
    validations:
      required: true

  - type: textarea
    id: context
    attributes:
      label: Context
      description: Provide any relevant context about your project or use case.
      placeholder: I'm trying to...

  - type: textarea
    id: attempted
    attributes:
      label: What Have You Tried?
      description: What have you already tried to solve this?
      placeholder: I have tried...

  - type: textarea
    id: code
    attributes:
      label: Relevant Code
      description: If applicable, provide relevant code snippets.
      render: cpp

  - type: input
    id: version
    attributes:
      label: WS Server Version
      description: What version of WS Server are you using?
      placeholder: "v1.0.0 or commit hash"

  - type: input
    id: environment
    attributes:
      label: Environment
      description: Your development environment (OS, compiler, etc.)
      placeholder: "Ubuntu 22.04, GCC 11"

  - type: checkboxes
    id: checklist
    attributes:
      label: Checklist
      description: Please confirm the following
      options:
        - label: I have searched existing issues and discussions
          required: true
        - label: I have checked the documentation and examples
          required: true
